@startuml
title UpdateAppointment System Sequence Diagram

actor Customer

participant AppointmentController as "<<Controller>>\nAppointmentController"
participant AppointmentService as "<<Service>>\nAppointmentService"
participant AppointmentRepository as "<<Repository>>\nAppointmentRepository"
participant Database as "<<Database>>\nDatabase"

Customer -> AppointmentController: PUT api/v1/customers/{customerId}/appointments/{appointmentId}
activate AppointmentController

AppointmentController -> AppointmentService: updateAppointmentByAppointmentId(appointmentRequestModel, appointmentId)
activate AppointmentService

AppointmentService -> AppointmentRepository: updateAppointmentByAppointmentId(appointmentRequestModel, appointmentId)
activate AppointmentRepository

AppointmentRepository -> Database: UPDATE appointments SET ... WHERE id = appointmentId
activate Database

Database --> AppointmentRepository: UpdateConfirmation
deactivate Database

AppointmentRepository --> AppointmentService: Appointment
deactivate AppointmentRepository

AppointmentService --> AppointmentController: AppointmentResponseModel
deactivate AppointmentService

AppointmentController --> Customer: AppointmentResponseModel
deactivate AppointmentController
@enduml
