@startuml

title GetCustomerAccountByCustomerId  System Sequence Diagram

actor Customer

participant CustomerAccountController as "<<Controller>>\nCustomerAccountController"
participant CustomerAccountService as "<<Service>>\nCustomerAccountService"
participant CustomerAccountRepository as "<<Repository>>\nCustomerAccountRepository"
participant Database as "<<Database>>\nDatabase"

Customer -> CustomerAccountController: GET /api/v1/customers/{customerId}
activate CustomerAccountController

CustomerAccountController -> CustomerAccountService: getCustomerAccountByCustomerId(customerId)
activate CustomerAccountService

CustomerAccountService -> CustomerAccountRepository: getCustomerAccountByCustomerId(customerId)
activate CustomerAccountRepository

CustomerAccountRepository -> Database: SELECT * FROM customers WHERE id = customerId
activate Database

Database --> CustomerAccountRepository: CustomerAccount
deactivate Database

CustomerAccountRepository --> CustomerAccountService: CustomerAccount
deactivate CustomerAccountRepository

CustomerAccountService --> CustomerAccountController: CustomerAccountResponseModel
deactivate CustomerAccountService

CustomerAccountController --> Customer: CustomerAccountResponseModel
deactivate CustomerAccountController
@enduml
