@startuml
title AddNewAppointmentToCustomerAccount System Sequence Diagram

actor Mechanic

participant AppointmentController as "<<Controller>>\nAppointmentController"
participant AppointmentService as "<<Service>>\nAppointmentService"
participant AppointmentRepository as "<<Repository>>\nAppointmentRepository"

Mechanic -> AppointmentController: POST /api/v1/customers/{customerId}/appointments
activate AppointmentController

AppointmentController -> AppointmentService: addAppointment(customerId, appointmentRequestModel)
activate AppointmentService

AppointmentService -> AppointmentRepository: save(newAppointment)
activate AppointmentRepository

AppointmentRepository --> AppointmentService: Appointment
deactivate AppointmentRepository

AppointmentService --> AppointmentController: AppointmentResponseModel
deactivate AppointmentService

AppointmentController --> Mechanic: AppointmentResponseModel
deactivate AppointmentController
@enduml
