@startuml
title AddVehicleToCustomerAccount System Sequence Diagram

actor Mechanic

participant VehicleController as "<<Controller>>\nVehicleController"
participant VehicleService as "<<Service>>\nVehicleService"
participant VehicleRepository as "<<Repository>>\nVehicleRepository"
participant Database as "<<Database>>\nDatabase"

Mechanic -> VehicleController: POST /api/v1/customers/{customerId}/vehicles
activate VehicleController

VehicleController -> VehicleService: addVehicleToCustomerAccount(customerId, vehicleRequestModel)
activate VehicleService

VehicleService -> VehicleRepository: save(newVehicle)
activate VehicleRepository

VehicleRepository -> Database: INSERT INTO vehicles ...
activate Database

Database --> VehicleRepository: Vehicle
deactivate Database

VehicleRepository --> VehicleService: Vehicle
deactivate VehicleRepository

VehicleService --> VehicleController: VehicleResponseModel
deactivate VehicleService

VehicleController --> Mechanic: VehicleResponseModel
deactivate VehicleController
@enduml
