@startuml
title GetAllCustomerInvoices System Sequence Diagram

actor Customer

participant InvoiceController as "<<Controller>>\nInvoiceController"
participant InvoiceService as "<<Service>>\nInvoiceService"
participant InvoiceRepository as "<<Repository>>\nInvoiceRepository"
participant Database as "<<Database>>\nDatabase"

Customer -> InvoiceController: GET /api/v1/customers/{customerId}/invoices
activate InvoiceController

InvoiceController -> InvoiceService: getAllInvoicesByCustomerId(customerId)
activate InvoiceService

InvoiceService -> InvoiceRepository: findAllInvoicesByCustomerId(String customerId)
activate InvoiceRepository

InvoiceRepository -> Database: SELECT * FROM invoices WHERE customerId = customerId
activate Database

Database --> InvoiceRepository: List<Invoice>
deactivate Database

InvoiceRepository --> InvoiceService: List<Invoice>
deactivate InvoiceRepository

InvoiceService --> InvoiceController: List<InvoiceResponseModel>
deactivate InvoiceService

InvoiceController --> Customer: List<InvoiceResponseModel>
deactivate InvoiceController
@enduml
