@startuml

actor Mechanic as "Mechanic"

participant VehicleController as "<<Controller>>\nVehicleController"
participant VehicleService as "<<Service>>\nVehicleService"
participant VehicleRepository as "<<Repository>>\nVehicleRepository"
participant Vehicle as "<<Entity>>\nVehicle"
participant Database as "<<Database>>\nDatabase"

Mechanic -> VehicleController: GET /api/v1/customers/{customerId}/vehicles
activate VehicleController

VehicleController -> VehicleService: getAllVehiclesForCustomer(customerId)
activate VehicleService

VehicleService -> VehicleRepository: findAllByCustomerId(customerId)
activate VehicleRepository

VehicleRepository -> Database: SELECT * FROM vehicles WHERE customerId = {customerId}
activate Database

Database --> VehicleRepository: vehiclesList: List<Vehicle>
deactivate Database

VehicleRepository --> VehicleService: vehiclesList
deactivate VehicleRepository

VehicleService --> VehicleController: vehicleResponseModels: List<VehicleResponseModel>
deactivate VehicleService

VehicleController --> Mechanic: vehicleResponseModels
deactivate VehicleController

@enduml
